require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'

# 日本語コメントを許可
Style/AsciiComments:
  Enabled: false

# ドキュメントコメントを不要に
Style/Documentation:
  Enabled: false

# 行の長さを緩和
Layout/LineLength:
  Max: 120

# メソッドの長さを緩和
Metrics/MethodLength:
  Max: 15

# クラスの長さを緩和
Metrics/ClassLength:
  Max: 150

# 文字列リテラルの統一（シングルクォート推奨）
Style/StringLiterals:
  EnforcedStyle: single_quotes

# ハッシュの記法統一
Style/HashSyntax:
  EnforcedStyle: ruby19